version: '3'
services:
  product-service:
    build: ./product-service
    ports:
      - "3001:3001"
  order-service:
    build: ./order-service
    ports:
      - "3002:3002"
  user-service:
    build: ./user-service
    ports:
      - "3003:3003"
